1.problem 


SELECT DISTINCT `OPEN_BRANCH_ID` as branchID FROM account;



2.problem


SELECT COUNT(DISTINCT `OPEN_BRANCH_ID`) as branchId FROM account;



3. problem

SELECT * FROM account WHERE AVAIL_BALANCE > 100;


4. problem

SELECT AVAIL_BALANCE FROM account GROUP BY AVAIL_BALANCE HAVING avg(AVAIL_BALANCE) > 5000


5. problem 

SELECT AVAIL_BALANCE FROM account GROUP BY AVAIL_BALANCE HAVING avg(AVAIL_BALANCE) > 1000;


6. problem

SELECT COUNT(CUST_ID), STATE FROM customer GROUP BY STATE HAVING COUNT(CUST_ID) > 5;

7. problem

SELECT OPEN_BRANCH_ID, AVG(AVAIL_BALANCE) as avg_balance FROM account WHERE STATUS = "ACTIVE" GROUP by OPEN_BRANCH_ID HAVING AVG(AVAIL_BALANCE) > 5000;


8. problem

SELECT * 
FROM employee
ORDER BY salary DESC
LIMIT 1 OFFSET 1;

9. problem

SELECT * FROM employee ORDER BY salary DESC LIMIT 1 OFFSET 0;
